"""removed test field

Revision ID: 2002926993ac
Revises: 9cbcdbcc7828
Create Date: 2026-03-22 21:38:22.422176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2002926993ac'
down_revision: Union[str, Sequence[str], None] = '9cbcdbcc7828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('test_field', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
