"""init routes

Revision ID: 9a77996b33db
Revises: 
Create Date: 2026-03-21 01:47:38.637309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a77996b33db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DOWNLOAD_QUEUE', 'DOWNLOADING', 'UPLOAD_QUEUE', 'UPLOADING', name='route_status'), nullable=False),
    sa.CheckConstraint("route_id <> ''", name='ck_routes_route_id_not_empty'),
    sa.PrimaryKeyConstraint('route_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
