"""added routes

Revision ID: 9cbcdbcc7828
Revises: 
Create Date: 2026-03-22 20:42:52.802822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbcdbcc7828'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DOWNLOAD_QUEUE', 'DOWNLOADING', 'UPLOAD_QUEUE', 'UPLOADING', 'FAILED', name='route_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('test_field', sa.String(), nullable=False),
    sa.CheckConstraint("route_id <> ''", name='ck_routes_route_id_not_empty'),
    sa.PrimaryKeyConstraint('route_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
