"""first migration

Revision ID: b2d0f7fbb5ad
Revises: cd10dfe23fa4
Create Date: 2026-04-09 15:32:45.439869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d0f7fbb5ad'
down_revision: Union[str, Sequence[str], None] = 'cd10dfe23fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_segment_run_review',
    sa.Column('job_run_num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('job_def_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED_FOR_LOADING', 'LOADING', 'LOADED', 'QUEUED_FOR_REMOVAL', 'REMOVING', 'REMOVED', 'FAILED', name='jobsegmentrunreviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_run_num', 'route_id', 'job_def_id', 'segment_id'], ['job_segment_run.job_run_num', 'job_segment_run.route_id', 'job_segment_run.job_def_id', 'job_segment_run.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_run_num', 'route_id', 'job_def_id', 'segment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_segment_run_review')
    # ### end Alembic commands ###
