"""first migration

Revision ID: c81b81b5553e
Revises: 
Create Date: 2026-04-13 18:29:30.226547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81b81b5553e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('IMAGE', 'JSON', 'PARQUET', name='artifact_kind_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_table('job_definitions',
    sa.Column('job_def_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('OBJECT_DETECTION', 'SEGMENTATION', 'DEPTH', 'ANNOTATION', name='job_type_enum'), nullable=False),
    sa.Column('implementation_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job_def_id')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('num_segments_expected', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DOWNLOAD_QUEUE', 'DOWNLOADING', 'UPLOAD_QUEUE', 'UPLOADING', 'FAILED', 'UPLOADED', name='route_status_enum'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("route_id <> ''", name='ck_routes_route_id_not_empty'),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('job_runs',
    sa.Column('job_run_num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_def_id', sa.BigInteger(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('camera', sa.Enum('FRONT_REGULAR', 'FRONT_WIDE', 'DRIVER', name='camera_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='job_status_enum'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_def_id'], ['job_definitions.job_def_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('job_run_num', 'job_def_id', 'route_id', 'camera')
    )
    op.create_table('segments',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DOWNLOAD_QUEUE', 'DOWNLOADING', 'UPLOAD_QUEUE', 'UPLOADING', 'FAILED', 'UPLOADED', name='segment_status_enum'), nullable=False),
    sa.Column('segment_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('segment_id >= 0', name='ck_segments_segment_id_non_negative'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('route_id', 'segment_id')
    )
    op.create_table('frames',
    sa.Column('frame_pk', sa.BigInteger(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('camera', sa.Enum('FRONT_REGULAR', 'FRONT_WIDE', 'DRIVER', name='camera_type_enum'), nullable=False),
    sa.Column('log_mono_time', sa.BigInteger(), nullable=True),
    sa.Column('openpilot_features', sa.JSON(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id', 'segment_id'], ['segments.route_id', 'segments.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('frame_pk')
    )
    op.create_table('job_segment_run',
    sa.Column('job_run_num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('job_def_id', sa.Integer(), nullable=False),
    sa.Column('camera', sa.Enum('FRONT_REGULAR', 'FRONT_WIDE', 'DRIVER', name='camera_type_enum'), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='job_segment_run_enum'), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ),
    sa.ForeignKeyConstraint(['job_run_num', 'route_id', 'job_def_id', 'camera'], ['job_runs.job_run_num', 'job_runs.route_id', 'job_runs.job_def_id', 'job_runs.camera'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_run_num', 'route_id', 'job_def_id', 'camera', 'segment_id')
    )
    op.create_table('segment_artifacts',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('FRAME_IMAGE', 'SEGMENT_LOG', 'COCO_EXPORT', 'DETECTION_JSON', 'SEGMENTATION_MASK', 'SEGMENTATION_MAP', 'DEPTH_MAP', name='artifact_role_enum'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id', 'segment_id'], ['segments.route_id', 'segments.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('route_id', 'segment_id', 'role')
    )
    op.create_table('frame_artifacts',
    sa.Column('frame_pk', sa.BigInteger(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('FRAME_IMAGE', 'SEGMENT_LOG', 'COCO_EXPORT', 'DETECTION_JSON', 'SEGMENTATION_MASK', 'SEGMENTATION_MAP', 'DEPTH_MAP', name='artifact_role_enum'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ),
    sa.ForeignKeyConstraint(['frame_pk'], ['frames.frame_pk'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('frame_pk', 'role')
    )
    op.create_table('job_segment_run_review',
    sa.Column('job_run_num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('job_def_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('camera', sa.Enum('FRONT_REGULAR', 'FRONT_WIDE', 'DRIVER', name='camera_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED_FOR_LOADING', 'LOADING', 'LOADED', 'QUEUED_FOR_REMOVAL', 'REMOVING', 'REMOVED', 'FAILED', name='job_segment_run_review_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('task_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_run_num', 'route_id', 'job_def_id', 'segment_id', 'camera'], ['job_segment_run.job_run_num', 'job_segment_run.route_id', 'job_segment_run.job_def_id', 'job_segment_run.segment_id', 'job_segment_run.camera'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_run_num', 'route_id', 'job_def_id', 'segment_id', 'camera')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_segment_run_review')
    op.drop_table('frame_artifacts')
    op.drop_table('segment_artifacts')
    op.drop_table('job_segment_run')
    op.drop_table('frames')
    op.drop_table('segments')
    op.drop_table('job_runs')
    op.drop_table('routes')
    op.drop_table('job_definitions')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
